functional:
 - Пользователь должен иметь возможность зарегестрироваться
 - Пользователь должен иметь возможность авторизоваться
 - Пользователь должен иметь возможность востановления пароля
 - Пользователь должен иметь возможность настройки аккаунта
 - Пользователь должен иметь возможность создавать игру
 - Пользователь должен иметь возможность присоединяться к созданой игре как участник
 - Пользователь должен иметь возможность присоединяться к созданой игре как зритель
 - Пользователь должен иметь возможность общения
 - Пользователь должен иметь возможность отсеживать статистику по играм
 - Пользователь должен иметь возможность создания собственных задач для решения
 - Пользователь должен иметь возможность просматривать историю игр
non-functional:
 - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
 - Сайт должен быть безопасным и защищать данные пользователя
 - Сайт должен быть удобным на мобильном устройстве
 - Сайт должен быть протестирован на совместимость с последними версиями браузеров
 - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
 - На сайте присутствует возможность просматривать запись игры
 - Во время игры присутствует возможность настройки редактора игрока
 - В случае поражения, игрок может вызвать опонента на реванш 
